### ISSUE TITLE
error when starting mpm 

### ISSUE THREAD

**Issue by h0rb** [iBuyMountainDew/mpm#2]
hi, when i try to launch mpm with 1.12.2-forge i get this error:
`
Caused by: java.lang.RuntimeException: org.lwjgl.LWJGLException: Could not open X display connection
        at org.lwjgl.opengl.Display.<clinit>(Display.java:141)
        ... 24 more
Caused by: org.lwjgl.LWJGLException: Could not open X display connection
        at org.lwjgl.opengl.LinuxDisplay.openDisplay(Native Method)
        at org.lwjgl.opengl.LinuxDisplay.incDisplay(LinuxDisplay.java:305)
        at org.lwjgl.opengl.LinuxDisplay.internAtom(LinuxDisplay.java:629)
        at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:734)
        at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
        ... 24 more
`

**Comment by BitBuf** [comment]
Install HeadlessForge first.
